config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :his
  resources :mz_guahao1_his

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'his#index'

  namespace :admin do
    resources :posts do
      collection do
        get :search
      end
    end
    resources :categories
  end

  resources :posts do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :posts
end

app/models/hi.rb
class Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_guahao1'
end

app/models/income.rb
class Income < ApplicationRecord
  establish_connection :qc
  self.table_name = 'ror_tongji_m_y'
end

app/models/mz_chufang1_hi.rb
class MzChufang1Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_chufang1'
end

app/models/mz_chufang2_hi.rb
class MzChufang2Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_chufang2'
end

app/models/mz_guahao1_hi.rb
class MzGuahao1Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_guahao1'
end

app/models/mz_guahao2_hi.rb
class MzGuahao2Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_guahao2'
end

app/models/mz_shoufei1_hi.rb
class MzShoufei1Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_shoufei1'
end

app/models/mz_yiji1_hi.rb
class MzYiji1Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_yiji1'
end

app/models/mz_yiji2_hi.rb
class MzYiji2Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_yiji2'
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  belongs_to :category, :optional => true
end

app/models/ror_tongji_m_y_hi.rb
class RorTongjiMYHi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'ror_tongji_m_y'
end
#暂未使用此model，因为出现未初始化的常量错误

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end

end

app/models/zy_bingrenxx_hi.rb
class ZyBingrenxxHi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'zy_bingrenxx'
end

app/models/zy_feiyong1_hi.rb
class ZyFeiyong1Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'zy_feiyong1'
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :set_post, only: [:show,:edit,:update, :destory]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :validate_search_key, only: [:search]
  before_filter :require_is_admin
  layout 'admin'

  def index
    @posts = Post.all.order("updated_at DESC").paginate(:page => params[:page], :per_page =>20)
  end

  def show
  end

  def new
    @post = Post.new
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create
    @post = Post.new(post_params)
    @post.category_id = params[:category_id]
    if @post.save
      redirect_to admin_posts_path
    else
      render :new
    end
  end

  def edit
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    @post.category_id = params[:category_id]
    if @post.update(post_params)
      redirect_to admin_posts_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path
  end

  def search
    if @query_string.present?
      search_result = Post.ransack(@search_criteria).result(:distinct => true)
      @posts = search_result.paginate(:page => params[:page], :per_page => 20)
    end
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/,"") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end

  def search_criteria(query_string)
    {:title_or_content_cont => query_string}
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end



end

app/controllers/his_controller.rb
class HisController < ApplicationController
  layout 'his'

  def index
    @rc = MzGuahao1Hi.connection.select_values("
      select sum(a.jiaoyilx)
      from mz_guahao1 a, mz_shoufei1 b
      where a.shoufeiid = b.shoufeiid
      and b.shoufeirq >= to_date(to_char(sysdate,'yyyy-mm-dd')||'00:00:00','yyyy-mm-dd hh24:mi:ss')
      ")
    @mz = MzYiji2Hi.connection.select_values("
        select sum(feiyonghj)
        from mz_shoufei1
        where  shoufeirq >= to_date(to_char(sysdate,'yyyy-mm-dd')||'00:00:00','yyyy-mm-dd hh24:mi:ss')
        ")

    @zy = ZyFeiyong1Hi.connection.select_values("
              select sum(jiesuanje)
              from zy_feiyong1
              where hesuanxm<>29
              and jifeirq >= to_date(to_char(sysdate,'yyyy-mm-dd')||'00:00:00','yyyy-mm-dd hh24:mi:ss')
              ")
    @rc_m = Income.connection.select_values("
              select sum(rc_m)
              from ror_tongji_m_y
              ")
    @mz_m = Income.connection.select_values("
              select sum(mz_m)
              from ror_tongji_m_y
              ")
    @zy_m = Income.connection.select_values("
              select sum(zy_m)
              from ror_tongji_m_y
              ")
    @rc_y = Income.connection.select_values("
              select sum(rc_y)
              from ror_tongji_m_y
              ")
    @mz_y = Income.connection.select_values("
              select sum(mz_y)
              from ror_tongji_m_y
              ")
    @zy_y = Income.connection.select_values("
              select sum(zy_y)
              from ror_tongji_m_y
              ")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :validate_search_key, only: [:search]
  # GET /posts
  # GET /posts.json
  def index
    if params[:category_id].blank?
      @posts = Post.all.order("updated_at DESC").paginate(:page => params[:page], :per_page => 20)
    else
      @posts = Post.where(category_id: params[:category_id]).order("updated_at DESC").paginate(:page => params[:page], :per_page => 20)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def search
    if @query_string.present?
      search_result = Post.ransack(@search_criteria).result(:distinct => true)
      @posts = search_result.paginate(:page => params[:page], :per_page => 20)
    end
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/,"") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end

  def search_criteria(query_string)
    {:title_or_content_cont => query_string}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :category_id)
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/his_helper.rb
module HisHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_highlight_title(post, query_string)
    excerpt_cont = excerpt(post.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end

  def render_highlight_content(post, query_string)
    excerpt_cont = excerpt(post.content, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/admin/posts/_form.html.erb
<%= simple_form_for [:admin,@post] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-post">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :content, input_html: { class: "form-control"}, as: :ckeditor %>
  </div>

  <%= select_tag(:category_id, options_for_select(@categories, :selected => @post.category_id), :prompt => 'Select one') %>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>

<% end %>

app/views/admin/posts/_posts_item.html.erb
<table class="table table-boldered">
  <thead>
    <tr>
      <td>Title</td>
      <td>Content</td>
      <td>Category</td>
      <td>Update Date</td>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= link_to(render_highlight_title(post, @query_string), admin_post_path(post)) %>
        </td>

        <td>
          <%= link_to(render_highlight_content(post, @query_string), admin_post_path(post)) %>

        </td>
        <td><%= post.category.try(:name) %></td>
        <td><%= post.updated_at.to_s(:ymd)  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/_search_bar.html.erb
<div class="col-md-10">
  <div class="col-sm-9 col-lg-8 col-lg-offset-2">
    <%= form_tag search_admin_posts_path, :method => :get, :class => "posts-search-form" do %>
      <div class="input-group">
        <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="search posts" >

        <span class="input-group-btn">
          <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    <% end %>
  </div>

app/views/admin/posts/edit.html.erb
<div class="col-md-10">
    <h4>编辑post</h4>

    <hr>
    <%= render "form" %>

</div>

app/views/admin/posts/index.html.erb
<div class="col-md-10">
<%= render "search_bar" %>
<div class="pull-right">
  <%= link_to("Add a post", new_admin_post_path, :class => "btn btn-default" ) %>
</div>

<br><br>

<table class="table table-boldered">
  <thead>
    <tr>
      <td>#</td>
      <td>Title</td>
      <td>Create Data</td>
      <td>Update Data</td>
      <td>Category</td>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>#</td>
        <td><%= link_to(post.title, admin_post_path(post)) %></td>
        <td><%= post.created_at.to_s(:ymd) %></td>
        <td><%= post.updated_at.to_s(:ymd)  %></td>
        <td><%= post.category.try(:name) %></td>
        <td>
          <%= link_to("Edit", edit_admin_post_path(post)) %>
          <%= link_to("Destroy", admin_post_path(post), :method => :delete, :data => { :confirm => "Are you sure?" }) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

</div>

app/views/admin/posts/new.html.erb
<div class="col-md-10">
    <h4>新增post</h4>

    <hr>
    <%= render "form" %>

</div>

app/views/admin/posts/search.html.erb
<%= render :partial => "admin/posts/search_bar" %>

<div class="col-md-10">

    <% if @posts.blank? %>
      <br>
      <h3 class="text-center">
        No posts matched yet, please try again.
      </h3>
    <% else %>
      <h3 class="text-center" style="margin-top: 30px;">Total find <%= @posts.count %> posts </h3>
      <hr />
        <%= render :partial => "posts_item", :collention => @posts, :as => :post %>
      <div class="text-center">
        <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
      </div>
    <% end %>
</div>

app/views/admin/posts/show.html.erb
<div class="col-md-10 show">
  <div class="pull-right">
    <%= link_to("Edit", edit_admin_post_path, :class => "btn btn-default" ) %>
  </div>

  <h2><%= @post.title %></h2>
  <p><%= sanitize @post.content %></p>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-post">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :content, input_html: { class: "form-control"}, as: :ckeditor %>
  </div>

  <%= select_tag(:category_id, options_for_select(@categories, :selected => @post.category_id), :prompt => 'Select one') %>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>

<% end %>

app/views/posts/_posts_item.html.erb
<table class="table table-boldered">
  <thead>
    <tr>
      <td>Title</td>
      <td>Content</td>
      <td>Category</td>
      <td>Update Date</td>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= link_to(render_highlight_title(post, @query_string), post_path(post)) %>
        </td>

        <td>
          <%= link_to(render_highlight_content(post, @query_string), post_path(post)) %>

        </td>
        <td><%= post.category.try(:name) %></td>
        <td><%= post.updated_at.to_s(:ymd)  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/_search_bar.html.erb
<div class="row">
  <div class="col-sm-9 col-lg-8 col-lg-offset-2">
    <%= form_tag search_posts_path, :method => :get, :class => "posts-search-form" do %>
      <div class="input-group">
        <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="search posts" >

        <span class="input-group-btn">
          <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    <% end %>
  </div>

app/views/posts/edit.html.erb
<div class="col-md-12">
    <h4>编辑post</h4>

    <hr>
    <%= render "form" %>

</div>

app/views/posts/index.html.erb
<div class="col-md-10">
  <%= render :partial => "posts/search_bar" %>

  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Create Data</td>
        <td>Update Data</td>
        <td>Category</td>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>#</td>
          <td><%= link_to(post.title, post_path(post)) %></td>
          <td><%= post.created_at.to_s(:ymd) %></td>
          <td><%= post.updated_at.to_s(:ymd)  %></td>
          <td><%= post.category.try(:name) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="col-md-12">
    <h4>新增post</h4>

    <hr>
    <%= render "form" %>

</div>

app/views/posts/search.html.erb
<%= render :partial => "posts/search_bar" %>

<div class="col-md-12">

    <% if @posts.blank? %>
      <br>
      <h3 class="text-center">
        No posts matched yet, please try again.
      </h3>
    <% else %>
      <h3 class="text-center" style="margin-top: 30px;">Total find <%= @posts.count %> posts </h3>
      <hr />
        <%= render :partial => "posts_item", :collention => @posts, :as => :post %>
      <div class="text-center">
        <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
      </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 show">
  <h2><%= @post.title %></h2>
  <p><%= sanitize @post.content %></p>
</div>