config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :his
  resources :mz_guahao1_his

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'his#index'

  namespace :admin do
    resources :posts do
      collection do
        get :search
      end
    end
    resources :categories
  end

  resources :posts do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :posts
end

app/models/hi.rb
class Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_guahao1'
end

app/models/income.rb
class Income < ApplicationRecord
  establish_connection :qc
  self.table_name = 'ror_tongji_m_y'
end

app/models/mz_chufang1_hi.rb
class MzChufang1Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_chufang1'
end

app/models/mz_chufang2_hi.rb
class MzChufang2Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_chufang2'
end

app/models/mz_guahao1_hi.rb
class MzGuahao1Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_guahao1'
end

app/models/mz_guahao2_hi.rb
class MzGuahao2Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_guahao2'
end

app/models/mz_shoufei1_hi.rb
class MzShoufei1Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_shoufei1'
end

app/models/mz_yiji1_hi.rb
class MzYiji1Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_yiji1'
end

app/models/mz_yiji2_hi.rb
class MzYiji2Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'mz_yiji2'
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  belongs_to :category, :optional => true
end

app/models/ror_tongji_m_y_hi.rb
class RorTongjiMYHi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'ror_tongji_m_y'
end
#暂未使用此model，因为出现未初始化的常量错误

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end

end

app/models/zy_bingrenxx_hi.rb
class ZyBingrenxxHi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'zy_bingrenxx'
end

app/models/zy_feiyong1_hi.rb
class ZyFeiyong1Hi < ApplicationRecord
  establish_connection :qc
  self.table_name = 'zy_feiyong1'
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/his_helper.rb
module HisHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_highlight_title(post, query_string)
    excerpt_cont = excerpt(post.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end

  def render_highlight_content(post, query_string)
    excerpt_cont = excerpt(post.content, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/common/_admin-sidebar.html.erb
<div class="col-md-2">
  <ul class="list-unstyled">
    <li class="side-list"><%= link_to('Post', admin_posts_path) %></li>
    <li class="side-list"><%= link_to('Category', admin_categories_path) %></li>
  </ul>
</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Document
        <br>Design by
        <a href="" target=_new>lisuji</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/posts">Document</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                  <% if !current_user %>
                    <li><%= link_to("注册", new_user_registration_path) %> </li>
                    <li><%= link_to("登入", new_user_session_path) %></li>
                  <% else %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <% if current_user.admin? %>
                        <li> <%= link_to("Admin Panel", admin_posts_path) %> </li>
                        <% end %>
                        <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                      </ul>
                    </li>
                  <% end %>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/common/_sidebar.html.erb
<div class="col-md-2">
  <ul class="list-unstyled">
    <% Category.all.each do |category| %>
      <li class="side-list"><%= link_to(category.name, posts_path(category_id: category.id)) %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Document</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= render "common/admin-sidebar" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Document</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/layouts/his.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>吉林大学口腔医院</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
          <nav class="navbar navbar-default his-nav" role="navigation">
                <a class="" href="" >吉林大学口腔医院</a>
          </nav>

            <%= yield %>
        </div>


    </body>
</html>